import Head from "next/head";
import { Hero } from "./components/HeroSection/Hero";
import { About } from "./components/AboutSection/AboutSection";
import { Features } from "./components/Features/Features";
import { ContactsSection } from "./components/Contacts/ContactsSection";
import { FAQ } from "./components/FAQSection/FAQ";
import { Footer } from "./components/Footer/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Luna - Agile Estimations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <div className="bg-dark w-screen h-fit pb-24">
          <About />
          <Features />
          <ContactsSection />
          <FAQ />
          <Footer />
        </div>
      </main>
    </>
  );
}
